### ISSUE TITLE
Does not work with new Gametest API bedrock version 1.19.40+

### ISSUE THREAD

**Issue by f4nk9** [Adr-hyng-OSS/Lumber-Axe#4]
Sadly modules have been renamed:
_mojang-gametest-> @minecraft/server-gametest 
mojang-minecraft-> @minecraft/server
mojang-minecraft-ui-> @minecraft/server-ui
mojang-minecraft-server-admin-> @minecraft/server-admin
mojang-net-> @minecraft/server-net_

Ref.: https://www.minecraft.net/sv-se/article/1-19-40-update-available-bedrock

Regards
f4nk9

**Comment by Adr-hyng** [comment]
Now is updated to v1.20.0 - v1.20.1.
